MASTER_ADR = 0
MAX_SLAVERS = 10
MAX_ARD = 16000
BRKAdr = 2 ^ 16

rstNone = 0
rstAssocReqSent = 1
rstWorking = 2

RFCOMMAND_CONNECT_REQUEST = 1
RFCOMMAND_CONNECT_OK = 1
RFCOMMAND_CONNECT_FAIL = 2
RFCOMMAND_TRANSMIT = 3
RFCOMMAND = { comand, srcAdr, destAdr }
