######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 24 22:24:42 2011
######################################################################

TEMPLATE = app
TARGET = starter
DESTDIR = ../../bin/
DEPENDPATH += . res
INCLUDEPATH += .
OBJECTS_DIR = ./debug

# DEFINES += QT_NO_DEBUG_OUTPUT QT_NO_WARNING_OUTPUT

# Input
HEADERS += mainWindow.h
FORMS += main.ui
SOURCES += main.cpp mainWindow.cpp
RESOURCES += res/res.qrc
